- block:
    - name: Update Pip
      pip:
        name: pip
        state: latest
        virtualenv: "{{ girder_virtualenv }}"
        virtualenv_python: "{{ girder_python | default(ansible_python.executable) }}"

    - name: Install Girder and plugin requirements
      pip:
        name: ".[plugins]"
        extra_args: "-e"
        chdir: "{{ girder_path }}"
        virtualenv: "{{ girder_virtualenv }}"
        virtualenv_python: "{{ girder_python | default(ansible_python.executable) }}"

    - set_fact:
        girder_install_executable: "{{ girder_virtualenv }}/bin/girder-install"
  when: girder_virtualenv is defined

- block:
    - name: Update Pip
      pip:
        name: pip
        state: latest
        executable: "{{ girder_pip | default(omit) }}"

    - name: Install Girder and plugin requirements
      pip:
        name: ".[plugins]"
        extra_args: "-e"
        chdir: "{{ girder_path }}"
        executable: "{{ girder_pip | default(omit) }}"
  when: girder_virtualenv is not defined
